**코랩을 구글 드라이브와 연결하기**

In [3]:
from google.colab import drive
drive.mount('/content/drive',force_remount=True)

Mounted at /content/drive


**numpy 패키지 불러오기**

In [1]:
import numpy as np

**데이터 파일 불러오기**

In [6]:
data = np.loadtxt("./drive/MyDrive/ML2024/data.txt",dtype=np.float32)
print(data.shape)
print(data)

(70, 5)
[[0.  4.9 3.  1.4 0.2]
 [0.  4.7 3.2 1.3 0.2]
 [0.  4.6 3.1 1.5 0.2]
 [0.  5.  3.6 1.4 0.2]
 [0.  5.4 3.9 1.7 0.4]
 [0.  4.6 3.4 1.4 0.3]
 [0.  5.  3.4 1.5 0.2]
 [0.  4.4 2.9 1.4 0.2]
 [0.  4.9 3.1 1.5 0.1]
 [0.  5.4 3.7 1.5 0.2]
 [0.  4.8 3.4 1.6 0.2]
 [0.  4.8 3.  1.4 0.1]
 [0.  4.3 3.  1.1 0.1]
 [0.  5.8 4.  1.2 0.2]
 [0.  5.7 4.4 1.5 0.4]
 [0.  5.4 3.9 1.3 0.4]
 [0.  5.1 3.5 1.4 0.3]
 [0.  5.7 3.8 1.7 0.3]
 [0.  5.1 3.8 1.5 0.3]
 [0.  5.4 3.4 1.7 0.2]
 [0.  5.1 3.7 1.5 0.4]
 [0.  4.6 3.6 1.  0.2]
 [0.  5.1 3.3 1.7 0.5]
 [0.  4.8 3.4 1.9 0.2]
 [1.  6.6 3.  4.4 1.4]
 [1.  6.8 2.8 4.8 1.4]
 [1.  6.7 3.  5.  1.7]
 [1.  6.  2.9 4.5 1.5]
 [1.  5.7 2.6 3.5 1. ]
 [1.  5.5 2.4 3.8 1.1]
 [1.  5.5 2.4 3.7 1. ]
 [1.  5.8 2.7 3.9 1.2]
 [1.  6.  2.7 5.1 1.6]
 [1.  5.4 3.  4.5 1.5]
 [1.  6.  3.4 4.5 1.6]
 [1.  6.7 3.1 4.7 1.5]
 [1.  6.3 2.3 4.4 1.3]
 [1.  5.6 3.  4.1 1.3]
 [1.  5.5 2.5 4.  1.3]
 [1.  5.5 2.6 4.4 1.2]
 [1.  6.1 3.  4.6 1.4]
 [1.  5.8 2.6 4.  1.2]
 [1.  5.  2.3 3.3 1. ]
 [1

**1. 배열 data의 차원 크기와 0부터 4번째의 행들을 출력하기**

In [9]:
print(data.shape)
data[0:4]

(70, 5)


array([[0. , 4.9, 3. , 1.4, 0.2],
       [0. , 4.7, 3.2, 1.3, 0.2],
       [0. , 4.6, 3.1, 1.5, 0.2],
       [0. , 5. , 3.6, 1.4, 0.2]], dtype=float32)

**2. data의 첫번째 열에 있는 고유한 값을 구하여 리스트에 저장하기**

In [13]:
list = np.unique(data[:,0])
print(list)

[0. 1. 2.]


data의 첫 번째 열에서 리스트에 저장된 고유한 값에 해당하는 행들을 추출하여 sub_data에 저장하기

sub_data의 첫번째 열을 제외한 나머지 열에 대해 열별 표준편차 계산하기

In [44]:
for i in range(len(list)):
    sub_data = data[data[:,0] == list[i]]
    a = sub_data[:,1:]
    std_val = np.std(a,axis=0)
    print(std_val)


[0.40026033 0.36853218 0.19751056 0.1040833 ]
[0.48016194 0.27660516 0.49775538 0.191304  ]
[0.5412909  0.28433627 0.39597672 0.2993105 ]
